config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

    get 'posts/about' => 'about#index', as: :about
    get 'search' => 'posts#search'

    resources :posts
    resources :authors

end

app/models/ad.rb
class Ad < ActiveRecord::Base
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :posts
  validates :name, :picture, presence: true

  def self.set_author(params)
    @author = Author.find_by! id: params
  end

  def self.order_authors_all
    @ordered_authors = Author.order(created_at: :desc)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author
  validates :title, :body, :author_id, :post_picture, presence: true
  validates :body, length: { minimum: 100}
  validates :title, length: { maximum: 100}
  validates :author_id, numericality: {only_integer: true}, allow_nil: true

  def self.order_posts_all
    @ordered_posts = Post.order(created_at: :desc)
  end


  def self.order_posts_four(params = 1)
    #is the ordering happening before the taking?
    @ordered_posts = Post.order(created_at: :desc).where.not("id = ?", params).take(4)
  end

  def self.set_post(params)
    @post = Post.find_by! id: params
  end

  def self.searched_posts(params)
    @searched_posts = Post.where("body LIKE ? OR title LIKE ?", "%#{params}%", "%#{params}%", "%#{params}%")
  end


end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @ad = Ad.all.sample
    @posts = Post.order_posts_four
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :pass_in_models

  def pass_in_models
    @posts = Post.order_posts_four(1)
    @ad = Ad.all.sample
  end

  def index
    @ordered_authors = Author.order_authors_all
  end

  def show
    @author = Author.set_author(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to author_path(@author.id)
    else
      @author_errors = @author.errors.messages
      render :new
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)
      redirect_to @author
    else
      render :edit
    end
  end

  def destroy
      @author = Author.find(params[:id])
      @author.destroy
      redirect_to authors_path
  end


  private

  def author_params
    params.require(:author).permit(:name, :picture)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :pass_in_models

  def pass_in_models
    @posts = Post.order_posts_four(1)
    @ad = Ad.all.sample
  end

  def index
    @ordered_posts = Post.order_posts_all
    @ad = Ad.all.sample
  end

  def show
    @ad = Ad.all.sample
    @post = Post.set_post(params[:id])
    @posts = Post.order_posts_four(params[:id])
  end

  def search
    @posts = Post.all.sort_by{|post| post.created_at} - [Post.all.last]
    @post = Post.all.sort_by{|post| post.created_at}.first
    @ad = Ad.all.sample
    @searched_posts = Post.searched_posts(params[:search_term])
    if @searched_posts[0]
      @search_message = "Here are the posts that match your search terms:"
    else
      @search_message = "I'm sorry, we were not able to find a match for your search term"
    end
  end

  def new
    #can't be Post.create else would sent to patch/update.
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post.id)
    else
      @post_errors = @post.errors.messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end



  private


  def post_params
    params.require(:post).permit(:author_id, :body, :title, :post_picture)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_background
    if @post && (1..5).to_a.include?(@post.id)
      "header-banner#{@post.id}"
    else
      "header-banner0"
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/about/_content_pictures.html.erb
<div class="row bigrow top-border top-pad text-center">
  <h1 class="bahia">Other Grass-Fed Content</h1>
</div>
<div class="row bigrow">
  <% posts.each do |post| %>
  <div class="col-md-3 no-side-padding tint-green">
  <%= link_to image_tag(post.post_picture, class: "uniform-height img-responsive"), post_path(post.id) %>
  <h2 class="relative-up"><%= post.title %></h2>
  </div>
  <% end %>
</div>

app/views/about/index.html.erb
<div class="row">
  <h1 class=" xs-small-margin font-kern link-visited"><span style="color:#591D0A"><h1>FOUNDER AND CONTENT MANAGER</h1>
</div>
<div class="row">
  <div class="hidden-xs hidden-sm col-md-4 bahia"><%= image_tag "HeadShot", class: "img-responsive img-rounded" %></div>
  <div class="col-md-4 text-center"><h2>Isaiah Fasoldt</h2></div>
</div>
<div class="row">
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

app/views/authors/_content_pictures.html.erb
<div class="row bigrow top-border top-pad text-center">
  <h1 class="bahia">Other Grass-Fed Content</h1>
</div>
<div class="row bigrow">
  <% posts.each do |post| %>
  <div class="col-md-3 no-side-padding tint-green">
  <%= link_to image_tag(post.post_picture, class: "uniform-height img-responsive"), post_path(post.id) %>
  <h2 class="relative-up"><%= post.title %></h2>
  </div>
  <% end %>
</div>

app/views/authors/_form.html.erb
<% if @author_errors %>
  <% @author_errors.each do |key, value| %>
    <p><%= "Error: #{key.to_s.capitalize} #{value.join(" and ")}." %></p>
  <% end %>
<% end %>

<%= form_for author do |f| %>
  <p>
    <%= f.label :name %>
  </p>
  <p>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :picture %>
  </p>
  <p>
    <%= f.text_field :picture %>
  </p>
  <%= f.submit data: {confirm: "If you do this, you will be creating a new author."} %>
<% end %>

app/views/authors/edit.html.erb
<h2> Edit: </h2>
<%= render partial: 'form', locals: {author: @author} %>

app/views/authors/index.html.erb
<h1>List Of Authors:</h1>
<% @ordered_authors.each do |author| %>
<div class="row">
  <h1 class=" xs-small-margin font-kern link-visited"><span style="color:#591D0A"><h3><%= link_to author.name, author_path(author.id) %></h3></span></h1>
</div>
<div class="row">
  <div class="hidden-xs hidden-sm col-md-4 bahia couriernew"><%= image_tag author.picture, class: "img-responsive img-extra-rounded" %> </div>
  <div class="hidden-xs hidden-sm col-md-5 lightgrey couriernew" id="date">on <a href="http://www.turfandcattle.com/date-this" class="social-media"> <%= author.created_at %></a></div>
</div>
<% end %>

app/views/authors/new.html.erb
<h2> Add Your New Author Here </h2>
<%= render partial: 'form', locals: {author: @author} %>

app/views/authors/show.html.erb
<h2 class="row text-center"> NEW Author Created: <%= @author.name %></h2>
<div class="row">
  <div class="hidden-xs hidden-sm col-md-12 bahia couriernew"><%= image_tag @author.picture, class: "img-responsive" %></div>
  <div class="hidden-xs hidden-sm col-md-5 lightgrey couriernew" id="date">on <a href="http://www.turfandcattle.com/date-this" class="social-media"> <%= @author.created_at %></a></div>
</div>

<div class="row">
  <%= link_to new_author_path, class: "col-xs-3 btn btn-info btn-sm btn-success" do %>
    <span class="glyphicon glyphicon-user-add"></span> Add Another Author
  <% end %>
  <%= link_to edit_author_path(@author.id), class: "col-xs-3 col-xs-offset-1 btn btn-info btn-sm btn-success" do %>
    <span class="glyphicon glyphicon-wrench"></span> Edit Author Info
  <% end %>
  <%= link_to author_path(@author.id), method: :delete, data: {confirm: "Really?"}, class: "col-xs-3 col-xs-offset-1 btn btn-danger btn-sm btn-success" do %>
    <span class="glyphicon glyphicon-user-remove"></span> Remove Author
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turf and Cattle</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <meta name="description" content="Your one stop for all things turf and cattle.">
    <meta name="viewport" content="width=device-width, initial-scale=1" >
    <%= csrf_meta_tags %>
  </head>
  <body >
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">
          <div class="row <%= set_background %>">
            <div class="col-xs-10 col-xs-offset-1">
              <div class="row">
                <div class="col-md-4 col-xs-12 header-font header-link-color"><%= image_tag "Cow", id: "logo" %>TURF & CATTLE CO. BLOG</div>
                <div class="col-md-1 col-xs-12 header-font"><%= link_to "ABOUT", about_path, class: "header-link-color" %></div>
                <div class="col-md-2 col-xs-12 header-font"><%= link_to "OUR AUTHORS", authors_path %></div>
                <div class="col-md-2 col-xs-12 header-font"><%= link_to "PAST CONTENT", posts_path %></div>
                <div class="col-md-3 col-xs-12 header-font">
                  <form class="row" action="/search" method="get">
                    <div  class="col-md-9">
                      <input class="search-field" type="text" name="search_term"/>
                    </div>
                    <div class="col-md-3 button button-padding-left">
                      <button class="button-rounded btn-secondary" type="submit">Search</button>
                    </div>
                  </form>
                </div>
              </div>
              <div class="row biggerrow">
                <div class="col-xs-7 col-xs-offset-5 title-font">TURF AND CATTLE CO.</div>
              </div>
              <div class="row">
                <div class="col-xs-6 col-xs-offset-6 subscript-font">An Iron Yard Academy Project Est. Summer 2016</div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-10 col-xs-offset-1">
          <div class="row bigrow">
            <div class="col-md-8">
              <%= yield %>
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="some-pad-top col-md-4 col-md-offset-4 col-sm-2 col-sm-offset-5 col-xs-4 col-xs-offset-4">
                  <%= image_tag "HeadShot",  class:"img-responsive img-rounded img-center" %>
                </div>
              </div>
              <div class="row text-center bahia couriernew ">
                  <h4 class="margin-bot">Isaiah Edward</h4>
              </div>
              <div class="row xs-left">
                  <div class="col-xs-12 text-center"><a href="https://twitter.com/IsaiahFasoldt" class="social-media">Twitter |</a> <a href="https://www.facebook.com/isaiah.fasoldt" class="social-media">Facebook |</a> <a href="https://www.instagram.com/ifasoldt/?hl=en" class="social-media">Instagram</a></div>
              </div>
              <div id="add" class="row lightgrey"> <%= image_tag @ad.ad_picture, class: "img-responsive bigrow" %><a href="http://www.google.com">About This Ad</a></div>
              <div class="xs-no-side-padding row padding-sides">
                <h4 class="bahia"><%= @ad.ad_title %></h4>
                <p class="lightgrey"><%= @ad.ad_body %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <%  if @posts %>
        <%= render partial: "content_pictures", locals: { posts: @posts} %>
      <% end %>
      <footer class="row background-redwood">
        <%= image_tag "TIY-logo.png", class:"col-md-1 col-md-offset-1 col-sm-3 col-sm-offset-2 col-xs-6 col-xs-offset-3" %>
        <div class="row hidden-md">
          <div class="col-md-3 text-white" id="copyright">"The Ironyard Copyright 2016, All Rights Reserved"</div>
          <div class="col-md-5 col-md-offset-2">
            <ul class="row">
              <li class="col-md-1 col-md-offset-1 no-side-padding"><a href="http://www.turfandcattle.com/help" class="link-white">Help</a></li>
                <li class="col-md-1 hidden-sm hidden-xs text-center  no-side-padding">|</li>
              <li class="col-md-2 no-side-padding"><a href="http://www.turfandcattle.com/contactus" class="link-white"> Contact Us</a></li>
              <li class="col-md-1 hidden-sm hidden-xs text-center no-side-padding">|</li>
              <li class="col-md-2 no-side-padding"><a href="http://www.turfandcattle.com/terms" class="link-white">Terms of Use</a></li>
              <li class="col-md-1 hidden-sm hidden-xs text-center no-side-padding">|</li>
              <li class="col-md-2 no-side-padding"><a href="http://www.turfandcattle.com/policies" class="link-white">Policies</a></li>
            </ul>
        </div>
      </div>
      </footer>
    </div>
  </body>
</html>

app/views/posts/_content_pictures.html.erb
<div class="row bigrow top-border top-pad text-center">
  <h1 class="bahia">Other Grass-Fed Content</h1>
</div>
<div class="row bigrow">
  <% posts.each do |post| %>
  <div class="col-md-3 no-side-padding tint-green">
  <%= link_to image_tag(post.post_picture, class: "uniform-height img-responsive"), post_path(post.id) %>
  <h2 class="relative-up"><%= post.title %></h2>
  </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<% if @post_errors %>
  <% @post_errors.each do |key, value| %>
    <p><%= "Error: #{key.to_s.capitalize} #{value.join(" and ")}." %></p>
  <% end %>
<% end %>

<%= form_for post, html: {class: "form-horizontal text-field"}  do |f| %>
  <p>
    <%= f.label :title %>
  </p>
  <p>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :author_id %>
  </p>
  <p>
    <%= f.collection_select("author_id", Author.all, :id, :name, include_blank: true) %>
  </p>
  <p>
    <%= f.label :post_picture %>
  </p>
  <p>
    <%= f.text_field :post_picture %>
  </p>
  <p>
    <%= f.label :body %>
  </p>
  <p>
    <%= f.text_area :body %>
  </p>
  <
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h2> Edit: </h2>
<%= render partial: 'form', locals: {post: @post} %>

app/views/posts/index.html.erb
<h1>List Of Posts:</h1>
<% @ordered_posts.each do |post| %>
<div class="row">
  <h1 class=" xs-small-margin font-kern link-visited"><span style="color:#591D0A"><h3><%= link_to post.title, post_path(post.id) %></h3></span></h1>
</div>
<div class="row">
  <div class="hidden-xs hidden-sm col-md-4 bahia couriernew"><%= image_tag post.author.picture, class: "img-responsive img-extra-rounded" %> <%= post.author.name %> </div>
  <div class="hidden-xs hidden-sm col-md-5 lightgrey couriernew" id="date">on <a href="http://www.turfandcattle.com/date-this" class="social-media"> <%= post.created_at %></a></div>
</div>
<%= simple_format(truncate(post.body, length: 300, separator:' '), class: "row pad-right almostbigrow") %>
<% end %>

app/views/posts/new.html.erb
<h2> Add Your New Post Here </h2>
<%= render partial: 'form', locals: {post: @post} %>

app/views/posts/search.html.erb
<h3><%= @search_message %></h3>
<% @searched_posts.each do |post| %>
<div class="row">
  <h1 class=" xs-small-margin font-kern link-visited"><span style="color:#591D0A"><h3><%= link_to post.title, post_path(post.id) %></h3></span></h1>
</div>
<div class="row">
  <div class="hidden-xs hidden-sm col-md-4 bahia couriernew"><%= image_tag post.author.picture, class: "img-responsive img-extra-rounded" %> <%= post.author.name %> </div>
  <div class="hidden-xs hidden-sm col-md-5 lightgrey couriernew" id="date">on <a href="http://www.turfandcattle.com/date-this" class="social-media"> <%= post.created_at %></a></div>
</div>
<%= simple_format(truncate(post.body, length: 200, separator:' '), class: "row pad-right almostbigrow") %>
<% end %>

app/views/posts/show.html.erb
<div class="row">
  <h1 class=" xs-small-margin font-kern link-visited"><span style="color:#591D0A"><%= link_to @post.title, post_path(@post.id) %> </span></h1>
</div>
<div class="row">
  <div class="hidden-xs hidden-sm col-md-4 bahia couriernew"><%= image_tag @post.author.picture, class: "img-responsive img-extra-rounded" %> <%= @post.author.name %> </div>
  <div class="hidden-xs hidden-sm col-md-5 lightgrey couriernew" id="date">on <a href="http://www.turfandcattle.com/date-this" class="social-media"> <%= @post.created_at %></a></div>
</div>
<%= simple_format(@post.body, class: "row pad-right almostbigrow") %>
<div class="row">
  <%= link_to new_post_path, class: "col-xs-3 btn btn-info btn-sm btn-success" do %>
    <span class="glyphicon glyphicon-edit"></span> Write
  <% end %>
  <%= link_to edit_post_path(@post.id), class: "col-xs-3 col-xs-offset-1 btn btn-info btn-sm btn-success" do %>
    <span class="glyphicon glyphicon-wrench"></span> Edit
  <% end %>
  <%= link_to post_path(@post.id), method: :delete, data: {confirm: "Really?"}, class: "col-xs-3 col-xs-offset-1 btn btn-danger btn-sm btn-success" do %>
    <span class="glyphicon glyphicon-fire"></span> DESTROY
  <% end %>
</div>